cart:
  app:
    persistence:
      provider: dynamodb
      dynamodb:
        tableName: retail-test-cart
        createTable: false
  dynamodb:
    create: false

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::350606136784:role/RetailTestCartDynamoDBRole


catalog:
  app:
    persistence:
      provider: in-memory



checkout:
  app:
    persistence:
      provider: redis
      redis:
        endpoint: retailstore-valkey-001.lk6esl.0001.apn2.cache.amazonaws.com:6379
        tls: false
    endpoints:
      orders: http://orders:80
  redis:
    create: false

  whatap:
    enabled: false

orders:
  app:
    persistence:
      provider: postgres
      endpoint: "retail-infra-postgres.cmnrhpznom2o.ap-northeast-2.rds.amazonaws.com"
      database: orders
      secret:
        create: false
        name: orders-db

    messaging:
      provider: in-memory
      rabbitmq:
        secret:
          create: false


  postgresql:
    create: false

  rabbitmq:
    create: false

ui:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: alb
  app:
    session:
      redis:
        endpoint: retailstore-valkey-001.lk6esl.0001.apn2.cache.amazonaws.com:6379
        tls: false